import { MESSAGE } from '@common/constant';
import { InvariantError } from './InvariantError';

export class DomainErrorTranslator {
  private static readonly directories: Record<string, Error> = {
    'REGISTER_USER.NOT_CONTAIN_NEEDED_PROPERTY': new InvariantError(MESSAGE.REGISTER_PAYLOAD_NOT_CONTAIN_NEEDED_PROPERTY),
    'REGISTER_USER.NOT_MEET_DATA_TYPE_SPECIFICATION': new InvariantError(MESSAGE.REGISTER_PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION),
    'REGISTER_USER.USERNAME_LIMIT_CHAR': new InvariantError(MESSAGE.REGISTER_PAYLOAD_USERNAME_LIMIT_CHAR),
    'REGISTER_USER.USERNAME_CONTAIN_RESTRICTED_CHARACTER': new InvariantError(MESSAGE.REGISTER_PAYLOAD_USERNAME_CONTAIN_RESTRICTED_CHARACTER),

    'USER_LOGIN.NOT_CONTAIN_NEEDED_PROPERTY': new InvariantError(MESSAGE.USER_LOGIN_NOT_CONTAIN_NEEDED_PROPERTY),
    'USER_LOGIN.NOT_MEET_DATA_TYPE_SPECIFICATION': new InvariantError(MESSAGE.USER_LOGIN_NOT_MEET_DATA_TYPE_SPECIFICATION),
    'REFRESH_AUTHENTICATION_USE_CASE.NOT_CONTAIN_REFRESH_TOKEN': new InvariantError(MESSAGE.REFRESH_AUTHENTICATION_USE_CASE_NOT_CONTAIN_REFRESH_TOKEN),
    'REFRESH_AUTHENTICATION_USE_CASE.PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION': new InvariantError(MESSAGE.REFRESH_TOKEN_NOT_MEET_DATA_TYPE_SPECIFICATION),
    'DELETE_AUTHENTICATION_USE_CASE.NOT_CONTAIN_REFRESH_TOKEN': new InvariantError(MESSAGE.DELETE_AUTHENTICATION_USE_CASE_NOT_CONTAIN_REFRESH_TOKEN),
    'DELETE_AUTHENTICATION_USE_CASE.PAYLOAD_NOT_MEET_DATA_TYPE_SPECIFICATION': new InvariantError(MESSAGE.DELETE_AUTHENTICATION_USE_CASE_NOT_MEET_DATA_TYPE_SPECIFICATION),
  };

  static translate(error: Error): Error {
    return DomainErrorTranslator.directories[error.message] || error;
  }
}
